// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp, setLogLevel } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-transactions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabaseClient.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";

// src/lib/mcp/env.ts
function readEnv(name) {
  const g = globalThis;
  const fromDeno = g.Deno?.env?.get?.(name);
  if (fromDeno) return fromDeno;
  const fromProcess = g.process?.env?.[name];
  return fromProcess || void 0;
}
function requireEnv(names) {
  for (const name of names) {
    const value = readEnv(name);
    if (value) return value;
  }
  throw new Error(
    `Configura\xE7\xE3o ausente no servidor: nenhuma das vari\xE1veis ${names.join(", ")} est\xE1 definida.`
  );
}

// src/lib/mcp/supabaseClient.ts
function supabasePublishableKey() {
  const direct = readEnv("SUPABASE_PUBLISHABLE_KEY")?.trim();
  if (direct) return direct;
  const keyset = readEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (value) => typeof value === "string" && value.trim().startsWith("sb_publishable_")
        );
        if (key) return key.trim();
      }
    } catch {
    }
  }
  return requireEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
}
function supabaseForUser(ctx) {
  const url = requireEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  const key = supabasePublishableKey();
  const token = ctx.getToken();
  if (!token) throw new Error("Token OAuth verificado n\xE3o dispon\xEDvel para consultar os dados.");
  return createClient(url, key, {
    global: {
      headers: {
        apikey: key,
        Authorization: `Bearer ${token}`
      }
    },
    auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false }
  });
}
function toolError(prefix, error) {
  let message;
  if (error instanceof Error) {
    message = error.message;
  } else if (error && typeof error === "object") {
    const e = error;
    message = [e.message, e.details, e.hint, e.code].filter(Boolean).join(" | ") || JSON.stringify(error);
  } else {
    message = String(error);
  }
  return {
    content: [{ type: "text", text: `${prefix}: ${message}` }],
    isError: true
  };
}

// src/lib/mcp/tools/list-transactions.ts
var dateSchema = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
var transactionSchema = z.object({
  id: z.string(),
  date: dateSchema,
  description: z.string(),
  value: z.number(),
  type: z.string(),
  final_category: z.string().nullable(),
  is_paid: z.boolean(),
  payment_method: z.string().nullable(),
  credit_card_id: z.string().nullable(),
  wallet_id: z.string().nullable(),
  invoice_month: z.string().nullable(),
  is_recurring: z.boolean()
});
var list_transactions_default = defineTool({
  name: "list_transactions",
  title: "Listar transa\xE7\xF5es",
  description: "Lista despesas e receitas do usu\xE1rio autenticado em um intervalo de datas (padr\xE3o: \xFAltimos 30 dias). Retorna id, data, descri\xE7\xE3o, valor, tipo, categoria, se est\xE1 paga e forma de pagamento.",
  inputSchema: {
    start_date: dateSchema.optional().describe("Data inicial ISO (YYYY-MM-DD). Padr\xE3o: 30 dias atr\xE1s."),
    end_date: dateSchema.optional().describe("Data final ISO (YYYY-MM-DD). Padr\xE3o: hoje."),
    type: z.enum(["income", "expense", "transfer"]).optional().describe("Filtrar por tipo."),
    limit: z.number().int().min(1).max(500).optional().describe("M\xE1ximo de registros (padr\xE3o 100).")
  },
  outputSchema: {
    transactions: z.array(transactionSchema),
    start_date: dateSchema,
    end_date: dateSchema
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, type, limit }, ctx) => {
    const invocation = {
      tool: "list_transactions",
      arguments: { start_date, end_date, type, limit },
      authenticated: ctx.isAuthenticated(),
      user_identified: Boolean(ctx.getUserId()),
      token_identified: Boolean(ctx.getToken()),
      client_identified: Boolean(ctx.getClientId())
    };
    console.info("[mcp.tool.request]", JSON.stringify(invocation));
    if (!ctx.isAuthenticated()) {
      console.warn("[mcp.tool.response]", JSON.stringify({ tool: invocation.tool, ok: false, reason: "not_authenticated" }));
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    try {
      const today = /* @__PURE__ */ new Date();
      const clampDate = (value) => {
        const [y, m, d] = value.split("-").map(Number);
        const lastDay = new Date(Date.UTC(y, m, 0)).getUTCDate();
        return `${y}-${String(m).padStart(2, "0")}-${String(Math.min(d, lastDay)).padStart(2, "0")}`;
      };
      const end = end_date ? clampDate(end_date) : today.toISOString().slice(0, 10);
      const start = start_date ? clampDate(start_date) : new Date(today.getTime() - 30 * 864e5).toISOString().slice(0, 10);
      const userId = ctx.getUserId();
      if (!userId) {
        console.warn("[mcp.tool.response]", JSON.stringify({ tool: invocation.tool, ok: false, reason: "missing_user_id" }));
        return toolError("Falha de autentica\xE7\xE3o", "Usu\xE1rio OAuth sem identificador");
      }
      const sb = supabaseForUser(ctx);
      let q = sb.from("expenses").select(
        "id,date,description,value,type,final_category,is_paid,payment_method,credit_card_id,wallet_id,invoice_month,is_recurring"
      ).eq("user_id", userId).gte("date", start).lte("date", end).order("date", { ascending: false }).limit(limit ?? 100);
      if (type) q = q.eq("type", type);
      const { data, error } = await q;
      if (error) {
        console.error("[mcp.tool.response]", JSON.stringify({ tool: invocation.tool, ok: false, database_code: error.code, message: error.message }));
        return toolError("Falha ao consultar as transa\xE7\xF5es", error);
      }
      const transactions = (data ?? []).map((row) => ({
        id: String(row.id),
        date: String(row.date),
        description: String(row.description),
        value: Number(row.value),
        type: String(row.type),
        final_category: row.final_category == null ? null : String(row.final_category),
        is_paid: Boolean(row.is_paid),
        payment_method: row.payment_method == null ? null : String(row.payment_method),
        credit_card_id: row.credit_card_id == null ? null : String(row.credit_card_id),
        wallet_id: row.wallet_id == null ? null : String(row.wallet_id),
        invoice_month: row.invoice_month == null ? null : String(row.invoice_month),
        is_recurring: Boolean(row.is_recurring)
      }));
      const payload = { transactions, start_date: start, end_date: end };
      console.info("[mcp.tool.response]", JSON.stringify({ tool: invocation.tool, ok: true, count: payload.transactions.length, start_date: start, end_date: end }));
      return {
        content: [{ type: "text", text: JSON.stringify(payload) }],
        structuredContent: payload
      };
    } catch (error) {
      console.error("[mcp.tool.exception]", error);
      return toolError("Erro de conex\xE3o ao consultar as transa\xE7\xF5es", error);
    }
  }
});

// src/lib/mcp/tools/create-transaction.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^4.4.3";
var create_transaction_default = defineTool2({
  name: "create_transaction",
  title: "Criar transa\xE7\xE3o",
  description: "Cria uma nova despesa ou receita para o usu\xE1rio autenticado. Use tipo 'expense' para despesa e 'income' para receita.",
  inputSchema: {
    description: z2.string().min(1).describe("Descri\xE7\xE3o curta da transa\xE7\xE3o."),
    value: z2.number().positive().describe("Valor absoluto (positivo) em BRL."),
    date: z2.string().describe("Data ISO YYYY-MM-DD."),
    type: z2.enum(["expense", "income"]).describe("Tipo da transa\xE7\xE3o."),
    category: z2.string().optional().describe("Nome/slug da categoria final."),
    is_paid: z2.boolean().optional().describe("Se j\xE1 foi pago/recebido. Padr\xE3o: true."),
    notes: z2.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("expenses").insert({
      user_id: ctx.getUserId(),
      description: input.description,
      value: input.value,
      date: input.date,
      type: input.type,
      final_category: input.category ?? "outros",
      category_ai: input.category ?? "outros",
      is_paid: input.is_paid ?? true,
      notes: input.notes ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Criada: ${data.id}` }],
      structuredContent: { transaction: data }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "Listar categorias",
  description: "Lista todas as categorias e subcategorias do usu\xE1rio autenticado.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("categories").select("id,name,icon,color,parent_id,active,sort_order").order("sort_order");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/month-summary.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^4.4.3";

// src/lib/creditCardPayments.ts
var PAYMENT_PREFIX_RE = /^pagamento(?: de)? fatura\s*/i;
function normalize(value) {
  return (value ?? "").trim().toLowerCase();
}
function getCreditCardPaymentCardId(item, creditCards = []) {
  if (item.credit_card_id) return item.credit_card_id;
  const description = normalize(item.description).replace(PAYMENT_PREFIX_RE, "");
  if (!description) return null;
  const matched = creditCards.find((card) => description.startsWith(normalize(card.name)));
  return matched?.id ?? null;
}
function isTrackedCreditCardPayment(item, creditCards = []) {
  if (item.type === "income" || item.type === "transfer") return false;
  const description = normalize(item.description);
  const category = normalize(item.final_category);
  const looksLikePayment = description.includes("fatura") || category.includes("cart\xE3o") || category.includes("cartao");
  if (!looksLikePayment) return false;
  return !!getCreditCardPaymentCardId(item, creditCards);
}
function isCreditCardPaymentLabel(description) {
  return PAYMENT_PREFIX_RE.test(description ?? "");
}
function getCreditCardPaymentLabelCardName(description) {
  return normalize(description).replace(PAYMENT_PREFIX_RE, "").split(" - ")[0];
}

// src/lib/invoiceHelpers.ts
function getClosingDay(card) {
  if (card.closing_strategy === "relative") {
    let cd = card.due_day - card.closing_days_before_due;
    if (cd <= 0) cd += 30;
    return cd;
  }
  return card.closing_day;
}
function buildClosingDate(year, month, closingDay) {
  const lastDay = new Date(year, month + 1, 0).getDate();
  const day = Math.min(closingDay, lastDay);
  return new Date(year, month, day);
}
function toMonthLabel(year, month) {
  return `${year}-${String(month + 1).padStart(2, "0")}`;
}
function getPaymentDate(purchaseDate, cardSettings) {
  const purchase = typeof purchaseDate === "string" ? /* @__PURE__ */ new Date(`${purchaseDate}T12:00:00`) : new Date(purchaseDate);
  const isCompact = "dueDay" in cardSettings;
  const dueDay = isCompact ? cardSettings.dueDay : cardSettings.due_day;
  const closingDay = isCompact ? cardSettings.closingDay : getClosingDay(cardSettings);
  const year = purchase.getFullYear();
  const month = purchase.getMonth();
  const day = purchase.getDate();
  let cycleYear = year;
  let cycleMonth = month;
  if (day > closingDay) {
    if (cycleMonth === 11) {
      cycleMonth = 0;
      cycleYear += 1;
    } else {
      cycleMonth += 1;
    }
  }
  const dueYear = cycleMonth === 11 ? cycleYear + 1 : cycleYear;
  const dueMonth = cycleMonth === 11 ? 0 : cycleMonth + 1;
  const dueLastDay = new Date(dueYear, dueMonth + 1, 0).getDate();
  return new Date(dueYear, dueMonth, Math.min(dueDay, dueLastDay));
}
function getInvoicePeriod(card, targetYear, targetMonth) {
  const closingDay = getClosingDay(card);
  const cycleMonth = targetMonth === 0 ? 11 : targetMonth - 1;
  const cycleYear = targetMonth === 0 ? targetYear - 1 : targetYear;
  const periodEnd = buildClosingDate(cycleYear, cycleMonth, closingDay);
  const prevCycleMonth = cycleMonth === 0 ? 11 : cycleMonth - 1;
  const prevCycleYear = cycleMonth === 0 ? cycleYear - 1 : cycleYear;
  const prevClosing = buildClosingDate(prevCycleYear, prevCycleMonth, closingDay);
  const periodStart = new Date(prevClosing);
  periodStart.setDate(periodStart.getDate() + 1);
  const dueLastDay = new Date(targetYear, targetMonth + 1, 0).getDate();
  const dueDate = new Date(targetYear, targetMonth, Math.min(card.due_day, dueLastDay));
  const today = /* @__PURE__ */ new Date();
  today.setHours(23, 59, 59, 999);
  let status = "open";
  if (today > dueDate) {
    status = "overdue";
  } else if (today > periodEnd) {
    status = "closed";
  }
  const monthLabel = `${targetYear}-${String(targetMonth + 1).padStart(2, "0")}`;
  return {
    cardId: card.id,
    cardName: card.name,
    closingDay,
    dueDay: card.due_day,
    limit: card.limit_amount,
    periodStart,
    periodEnd,
    dueDate,
    monthLabel,
    status
  };
}
function matchExpensesToInvoice(expenses, period) {
  const dueLabel = period.monthLabel;
  const matched = expenses.filter((e) => {
    if (e.credit_card_id !== period.cardId) return false;
    if (e.type === "income" || e.type === "transfer") return false;
    if (isCreditCardPaymentLabel(e.description)) return false;
    if (e.invoice_month) {
      return e.invoice_month === dueLabel;
    }
    const paymentDate = getPaymentDate(e.date, { closingDay: period.closingDay, dueDay: period.dueDay });
    const paymentLabel = toMonthLabel(paymentDate.getFullYear(), paymentDate.getMonth());
    return paymentLabel === dueLabel;
  });
  const total = matched.reduce((s, e) => s + e.value, 0);
  const normalizedCardName = period.cardName.trim().toLowerCase();
  const isPaid = expenses.some((e) => {
    if (e.type !== "expense" || !e.invoice_month || e.invoice_month !== dueLabel || !e.wallet_id) return false;
    if (!isCreditCardPaymentLabel(e.description)) return false;
    if (e.credit_card_id) return e.credit_card_id === period.cardId;
    const legacyCardName = getCreditCardPaymentLabelCardName(e.description);
    return legacyCardName === normalizedCardName;
  });
  let status = isPaid ? "paid" : period.status;
  if (total <= 0 && status === "overdue") {
    status = "closed";
  }
  return { ...period, status, transactions: matched, total };
}

// src/lib/invoiceCashFlow.ts
function toMonthLabel2(year, month) {
  return `${year}-${String(month + 1).padStart(2, "0")}`;
}
function toDateKey(date) {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
}
function parseMonthLabel(label) {
  const [year, month] = label.split("-").map(Number);
  return { year, month: month - 1 };
}
function normalizeCardName(name) {
  return (name ?? "").trim().toLowerCase();
}
function getLegacyPaymentCardName(description) {
  return normalizeCardName(getCreditCardPaymentLabelCardName(description));
}
function isInvoicePaymentRecord(expense) {
  return expense.type === "expense" && !!expense.invoice_month && !!expense.wallet_id && isCreditCardPaymentLabel(expense.description);
}
function resolveExpenseMonthLabel(expense, cardsById) {
  if (expense.invoice_month) return expense.invoice_month;
  if (!expense.credit_card_id) return null;
  const card = cardsById.get(expense.credit_card_id);
  if (!card) return null;
  const paymentDate = getPaymentDate(expense.date, card);
  return toMonthLabel2(paymentDate.getFullYear(), paymentDate.getMonth());
}
function findInvoicePaymentRecord(expenses, period) {
  const normalizedCardName = normalizeCardName(period.cardName);
  return expenses.filter((expense) => {
    if (!isInvoicePaymentRecord(expense) || expense.invoice_month !== period.monthLabel) return false;
    if (expense.credit_card_id) return expense.credit_card_id === period.cardId;
    return getLegacyPaymentCardName(expense.description) === normalizedCardName;
  }).sort((a, b) => a.date.localeCompare(b.date))[0];
}
function buildInvoiceCashEvents(creditCards, expenses) {
  if (creditCards.length === 0 || expenses.length === 0) return [];
  const cardsById = new Map(creditCards.map((card) => [card.id, card]));
  const cardsByName = new Map(creditCards.map((card) => [normalizeCardName(card.name), card]));
  const labelsByCard = /* @__PURE__ */ new Map();
  const addLabel = (cardId, label) => {
    if (!label) return;
    if (!labelsByCard.has(cardId)) labelsByCard.set(cardId, /* @__PURE__ */ new Set());
    labelsByCard.get(cardId).add(label);
  };
  expenses.forEach((expense) => {
    if (expense.type !== "expense") return;
    if (expense.credit_card_id && cardsById.has(expense.credit_card_id)) {
      addLabel(expense.credit_card_id, resolveExpenseMonthLabel(expense, cardsById));
      return;
    }
    if (!isInvoicePaymentRecord(expense)) return;
    const matchedCard = cardsByName.get(getLegacyPaymentCardName(expense.description));
    if (matchedCard) addLabel(matchedCard.id, expense.invoice_month ?? null);
  });
  const typedExpenses = expenses;
  const events = [];
  labelsByCard.forEach((labels, cardId) => {
    const card = cardsById.get(cardId);
    if (!card) return;
    Array.from(labels).sort().forEach((label) => {
      const { year, month } = parseMonthLabel(label);
      const invoice = matchExpensesToInvoice(typedExpenses, getInvoicePeriod(card, year, month));
      if (invoice.total <= 0) return;
      const paymentRecord = findInvoicePaymentRecord(expenses, invoice);
      events.push({
        amount: invoice.total,
        cardId,
        date: paymentRecord?.date ?? toDateKey(invoice.dueDate),
        monthLabel: invoice.monthLabel
      });
    });
  });
  return events.sort(
    (a, b) => a.date.localeCompare(b.date) || a.cardId.localeCompare(b.cardId) || a.monthLabel.localeCompare(b.monthLabel)
  );
}
function sumInvoiceCashEventsBeforeDate(events, cutoffDate) {
  return events.reduce((sum, event) => event.date < cutoffDate ? sum + event.amount : sum, 0);
}
function groupInvoiceCashEventsByDay(events, startDate, endDate) {
  return events.reduce((acc, event) => {
    if (event.date < startDate || event.date > endDate) return acc;
    acc[event.date] = (acc[event.date] || 0) + event.amount;
    return acc;
  }, {});
}

// src/lib/projectedBalanceMath.ts
function buildDailyBalanceMap({
  monthExpenses,
  invoiceExpenses,
  creditCards,
  startDate,
  endDate,
  startingBalance,
  isCreditCardPayment
}) {
  const nonCcFlowByDay = {};
  monthExpenses.forEach((expense) => {
    if (expense.type === "transfer") return;
    if (expense.credit_card_id) return;
    if (isCreditCardPayment(expense)) return;
    if (expense.date < startDate || expense.date > endDate) return;
    nonCcFlowByDay[expense.date] = nonCcFlowByDay[expense.date] || 0;
    nonCcFlowByDay[expense.date] += expense.type === "income" ? expense.value : -expense.value;
  });
  const invoiceTotalByDay = groupInvoiceCashEventsByDay(
    buildInvoiceCashEvents(creditCards, invoiceExpenses.length > 0 ? invoiceExpenses : monthExpenses),
    startDate,
    endDate
  );
  const allDayKeys = Array.from(
    /* @__PURE__ */ new Set([...Object.keys(nonCcFlowByDay), ...Object.keys(invoiceTotalByDay)])
  ).sort();
  let runningBalance = startingBalance;
  const balanceMap = {};
  allDayKeys.forEach((day) => {
    runningBalance += nonCcFlowByDay[day] || 0;
    runningBalance -= invoiceTotalByDay[day] || 0;
    balanceMap[day] = runningBalance;
  });
  return {
    balanceMap,
    nonCcFlowByDay,
    invoiceTotalByDay
  };
}
function computeProjectedMonthResult({
  effectiveMonthExpenses,
  invoiceTotal,
  invoiceByCategory,
  startingBalance,
  isCreditCardPayment
}) {
  const nonTransfers = effectiveMonthExpenses.filter((expense) => expense.type !== "transfer");
  const totalIncome = nonTransfers.filter((expense) => expense.type === "income").reduce((sum, expense) => sum + expense.value, 0);
  const debitExpense = nonTransfers.filter(
    (expense) => expense.type !== "income" && !expense.credit_card_id && !isCreditCardPayment(expense)
  ).reduce((sum, expense) => sum + expense.value, 0);
  const totalExpense = debitExpense + invoiceTotal;
  const byCategory = { ...invoiceByCategory };
  nonTransfers.filter(
    (expense) => expense.type !== "income" && !expense.credit_card_id && !isCreditCardPayment(expense)
  ).forEach((expense) => {
    byCategory[expense.final_category] = (byCategory[expense.final_category] || 0) + expense.value;
  });
  const largest = Object.entries(byCategory).sort((a, b) => b[1] - a[1])[0];
  return {
    totalIncome,
    totalExpense,
    balance: totalIncome - totalExpense,
    projectedBalance: startingBalance + totalIncome - totalExpense,
    largestCategory: largest ? { name: largest[0], total: largest[1], categoryKey: largest[0] } : null
  };
}

// src/lib/projectedInvoiceTotals.ts
function parseMonthLabel2(label) {
  const [year, month] = label.split("-").map(Number);
  return { year, month: month - 1 };
}
function computeInvoiceTotalsForCashWindow({
  creditCards,
  expenses,
  startDate,
  endDate
}) {
  if (creditCards.length === 0 || expenses.length === 0) {
    return { total: 0, byCategory: {} };
  }
  const cardsById = new Map(creditCards.map((card) => [card.id, card]));
  const events = buildInvoiceCashEvents(creditCards, expenses).filter(
    (event) => event.date >= startDate && event.date < endDate
  );
  let total = 0;
  const byCategory = {};
  const seenInvoices = /* @__PURE__ */ new Set();
  events.forEach((event) => {
    const invoiceKey = `${event.cardId}|${event.monthLabel}`;
    if (seenInvoices.has(invoiceKey)) return;
    seenInvoices.add(invoiceKey);
    const card = cardsById.get(event.cardId);
    if (!card) return;
    const { year, month } = parseMonthLabel2(event.monthLabel);
    const invoice = matchExpensesToInvoice(expenses, getInvoicePeriod(card, year, month));
    if (invoice.total <= 0) return;
    total += invoice.total;
    invoice.transactions.forEach((tx) => {
      byCategory[tx.final_category] = (byCategory[tx.final_category] || 0) + tx.value;
    });
  });
  return { total, byCategory };
}

// src/lib/recurringProjection.ts
function normalizeRecurringDescription(description) {
  return (description ?? "").trim().toLowerCase();
}
function buildRecurringLooseSignature(type, description) {
  return `${type}|${normalizeRecurringDescription(description)}`;
}
function buildRecurringSignature(type, value, description) {
  return `${type}|${normalizeRecurringDescription(description)}|${Number(value).toFixed(2)}`;
}
function buildRecurringExceptionSignature(templateId, occurrenceDate) {
  return `${templateId}|${occurrenceDate}`;
}
function shouldProjectRecurringInMonth(templateDate, selectedYear, selectedMonth, frequency) {
  const template = /* @__PURE__ */ new Date(`${templateDate}T12:00:00`);
  const templateMonthIndex = template.getFullYear() * 12 + template.getMonth();
  const selectedMonthIndex = selectedYear * 12 + selectedMonth;
  if (selectedMonthIndex < templateMonthIndex) return false;
  if (frequency === "yearly") {
    return template.getMonth() === selectedMonth;
  }
  return true;
}
function buildMaterializedRecurringSignature(item) {
  return [
    item.type,
    normalizeRecurringDescription(item.description),
    item.final_category ?? "",
    item.wallet_id ?? "",
    item.credit_card_id ?? "",
    item.payment_method ?? "",
    item.project_id ?? ""
  ].join("|");
}
function hideMaterializedRecurringTemplates(items) {
  const materializedSignatures = new Set(
    items.filter((item) => !item.is_recurring).map((item) => buildMaterializedRecurringSignature(item))
  );
  return items.filter((item) => !(item.is_recurring && materializedSignatures.has(buildMaterializedRecurringSignature(item))));
}

// src/lib/mcp/monthProjection.ts
var EXPENSE_COLS = "id, description, value, date, type, final_category, category_ai, credit_card_id, wallet_id, destination_wallet_id, is_paid, is_recurring, frequency, installments, installment_group_id, installment_info, invoice_month, payment_method, notes, tags, project_id, debt_id, created_at";
function pad(value) {
  return String(value).padStart(2, "0");
}
function daysInMonthOf(month) {
  const [year, monthNumber] = month.split("-").map(Number);
  return new Date(year, monthNumber, 0).getDate();
}
async function computeMonthProjection(sb, month) {
  const [year, monthNumber] = month.split("-").map(Number);
  const monthIndex = monthNumber - 1;
  const daysInMonth = daysInMonthOf(month);
  const startDate = `${month}-01`;
  const endDate = `${month}-${pad(daysInMonth)}`;
  const endExclusive = `${monthNumber === 12 ? year + 1 : year}-${pad(monthNumber === 12 ? 1 : monthNumber + 1)}-01`;
  const [monthRes, ccRes, invoicePaymentsRes, historicalRes, cardsRes, walletsRes, exceptionsRes, templatesRes] = await Promise.all([
    sb.from("expenses").select(EXPENSE_COLS).gte("date", startDate).lt("date", endExclusive).order("date"),
    sb.from("expenses").select(EXPENSE_COLS).not("credit_card_id", "is", null),
    sb.from("expenses").select(EXPENSE_COLS).is("credit_card_id", null).not("invoice_month", "is", null).like("description", "Pagamento fatura%"),
    sb.from("expenses").select(EXPENSE_COLS).lt("date", startDate).is("credit_card_id", null),
    sb.from("credit_cards").select("*"),
    sb.from("wallets").select("id, name, initial_balance"),
    sb.from("recurring_exceptions").select("template_id, occurrence_date"),
    sb.from("expenses").select(EXPENSE_COLS).eq("is_recurring", true)
  ]);
  const firstError = [monthRes, ccRes, invoicePaymentsRes, historicalRes, cardsRes, walletsRes, templatesRes].find(
    (r) => r.error
  );
  if (firstError?.error) throw new Error(firstError.error.message ?? JSON.stringify(firstError.error));
  const ccExpenses = ccRes.data ?? [];
  const paymentExpenses = invoicePaymentsRes.data ?? [];
  const ccIds = new Set(ccExpenses.map((e) => e.id));
  const invoiceExpenses = [...ccExpenses, ...paymentExpenses.filter((p) => !ccIds.has(p.id))];
  const creditCards = cardsRes.data ?? [];
  const wallets = walletsRes.data ?? [];
  const recurringTemplates = templatesRes.data ?? [];
  const exceptionSet = new Set(
    (exceptionsRes.data ?? []).map((e) => buildRecurringExceptionSignature(e.template_id, e.occurrence_date))
  );
  const visibleMonthExpenses = hideMaterializedRecurringTemplates(monthRes.data ?? []);
  const visibleHistorical = hideMaterializedRecurringTemplates(historicalRes.data ?? []);
  const isCCPayment = (e) => isTrackedCreditCardPayment(e, creditCards);
  const realSignatures = new Set(
    visibleMonthExpenses.map((e) => buildRecurringSignature(e.type, e.value, e.description))
  );
  const realLooseSignatures = new Set(
    visibleMonthExpenses.map((e) => buildRecurringLooseSignature(e.type, e.description))
  );
  const materializedSignatures = new Set(
    visibleMonthExpenses.filter((e) => !e.is_recurring).map((e) => buildMaterializedRecurringSignature(e))
  );
  const realIds = new Set(visibleMonthExpenses.map((e) => e.id));
  const virtualEntries = [];
  recurringTemplates.forEach((r) => {
    if (realIds.has(r.id)) return;
    if (!shouldProjectRecurringInMonth(r.date, year, monthIndex, r.frequency)) return;
    if (r.type === "transfer" || r.credit_card_id) return;
    if (realSignatures.has(buildRecurringSignature(r.type, r.value, r.description)) || realLooseSignatures.has(buildRecurringLooseSignature(r.type, r.description)) || materializedSignatures.has(buildMaterializedRecurringSignature(r)))
      return;
    const origDay = (/* @__PURE__ */ new Date(`${r.date}T12:00:00`)).getDate();
    const occurrenceDate = `${month}-${pad(Math.min(origDay, daysInMonth))}`;
    if (exceptionSet.has(buildRecurringExceptionSignature(r.id, occurrenceDate))) return;
    virtualEntries.push({ ...r, date: occurrenceDate, is_paid: false, is_projected: true });
  });
  const effectiveMonthExpenses = [...visibleMonthExpenses, ...virtualEntries];
  const walletSum = wallets.reduce((s, w) => s + Number(w.initial_balance ?? 0), 0);
  const historicalNonTransfers = visibleHistorical.filter((e) => e.type !== "transfer");
  const historicalIncome = historicalNonTransfers.filter((e) => e.type === "income").reduce((s, e) => s + Number(e.value), 0);
  const historicalDebit = historicalNonTransfers.filter((e) => e.type !== "income" && !isCCPayment(e)).reduce((s, e) => s + Number(e.value), 0);
  const invoiceCashEvents = buildInvoiceCashEvents(creditCards, invoiceExpenses);
  const invoicesBefore = sumInvoiceCashEventsBeforeDate(invoiceCashEvents, startDate);
  const startingBalance = walletSum + historicalIncome - historicalDebit - invoicesBefore;
  const invoiceTotals = computeInvoiceTotalsForCashWindow({
    creditCards,
    expenses: invoiceExpenses.length > 0 ? invoiceExpenses : effectiveMonthExpenses,
    startDate,
    endDate: endExclusive
  });
  const totals = computeProjectedMonthResult({
    effectiveMonthExpenses,
    invoiceTotal: invoiceTotals.total,
    invoiceByCategory: invoiceTotals.byCategory,
    startingBalance,
    isCreditCardPayment: isCCPayment
  });
  const daily = buildDailyBalanceMap({
    monthExpenses: effectiveMonthExpenses,
    invoiceExpenses,
    creditCards,
    startDate,
    endDate,
    startingBalance,
    isCreditCardPayment: isCCPayment
  });
  return {
    month,
    year,
    monthNumber,
    daysInMonth,
    startDate,
    endDate,
    startingBalance,
    effectiveMonthExpenses,
    invoiceTotals,
    totals,
    daily,
    creditCards
  };
}

// src/lib/mcp/tools/month-summary.ts
var month_summary_default = defineTool4({
  name: "month_summary",
  title: "Resumo do m\xEAs",
  description: "Resume receitas, despesas e saldo do m\xEAs (YYYY-MM) usando exatamente o mesmo motor de proje\xE7\xE3o das p\xE1ginas do app: saldo inicial (fim do m\xEAs anterior), receitas e despesas previstas (incluindo n\xE3o pagas, recorrentes projetadas e faturas de cart\xE3o) e saldo previsto do fim do m\xEAs. Tamb\xE9m informa os valores j\xE1 realizados (pagos).",
  inputSchema: {
    month: z3.string().regex(/^\d{4}-\d{2}$/).describe("M\xEAs no formato YYYY-MM.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ month }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    try {
      const sb = supabaseForUser(ctx);
      const { startingBalance, totals, invoiceTotals, effectiveMonthExpenses, daily, endDate } = await computeMonthProjection(sb, month);
      let paidIncome = 0;
      let paidExpense = 0;
      for (const e of effectiveMonthExpenses) {
        if (!e.is_paid || e.type === "transfer" || e.credit_card_id) continue;
        if (e.type === "income") paidIncome += Number(e.value);
        else paidExpense += Number(e.value);
      }
      const summary = {
        month,
        starting_balance: startingBalance,
        projected_income: totals.totalIncome,
        projected_expense: totals.totalExpense,
        projected_month_balance: totals.balance,
        projected_end_of_month_balance: totals.projectedBalance,
        end_of_month_balance_check: daily.balanceMap[endDate] ?? totals.projectedBalance,
        invoice_total: invoiceTotals.total,
        largest_category: totals.largestCategory,
        realized_income: paidIncome,
        realized_expense: paidExpense,
        realized_balance: paidIncome - paidExpense
      };
      return {
        content: [{ type: "text", text: JSON.stringify(summary) }],
        structuredContent: summary
      };
    } catch (error) {
      return toolError("Falha ao resumir o m\xEAs", error);
    }
  }
});

// src/lib/mcp/tools/list-wallets.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_wallets_default = defineTool5({
  name: "list_wallets",
  title: "Listar carteiras",
  description: "Lista carteiras e ativos do usu\xE1rio com saldo atual e moeda.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_i, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("wallets").select("id,name,asset_type,current_balance,initial_balance,currency");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { wallets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-credit-cards.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_credit_cards_default = defineTool6({
  name: "list_credit_cards",
  title: "Listar cart\xF5es de cr\xE9dito",
  description: "Lista cart\xF5es de cr\xE9dito do usu\xE1rio com limite, dia de fechamento e vencimento.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_i, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("credit_cards").select("id,name,limit_amount,closing_day,due_day,closing_strategy");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { credit_cards: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/month-transactions.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^4.4.3";
var month_transactions_default = defineTool7({
  name: "month_transactions",
  title: "Transa\xE7\xF5es do m\xEAs com saldo projetado",
  description: "Retorna a mesma vis\xE3o da p\xE1gina de Transa\xE7\xF5es de um m\xEAs (YYYY-MM): todas as transa\xE7\xF5es do m\xEAs (incluindo recorrentes projetadas e pagamentos de fatura de cart\xE3o), agrupadas por dia, com o saldo projetado acumulado ao final de cada dia, al\xE9m do saldo inicial e do saldo previsto do fim do m\xEAs.",
  inputSchema: {
    month: z4.string().describe("M\xEAs no formato YYYY-MM.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ month }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    if (!/^\d{4}-\d{2}$/.test(month)) {
      return { content: [{ type: "text", text: "Formato inv\xE1lido. Use YYYY-MM." }], isError: true };
    }
    try {
      const sb = supabaseForUser(ctx);
      const projection = await computeMonthProjection(sb, month);
      const { daysInMonth, startingBalance, effectiveMonthExpenses, invoiceTotals, totals, daily } = projection;
      const { balanceMap, nonCcFlowByDay, invoiceTotalByDay } = daily;
      const byDay = /* @__PURE__ */ new Map();
      effectiveMonthExpenses.forEach((e) => {
        if (!byDay.has(e.date)) byDay.set(e.date, []);
        byDay.get(e.date).push({
          id: e.id,
          description: e.description,
          value: Number(e.value),
          type: e.type,
          category: e.final_category,
          is_paid: !!e.is_paid,
          payment_method: e.payment_method,
          credit_card_id: e.credit_card_id ?? null,
          invoice_month: e.invoice_month ?? null,
          is_recurring: !!e.is_recurring,
          is_projected: !!e.is_projected,
          notes: e.notes ?? null
        });
      });
      let running = startingBalance;
      const days = [];
      for (let d = 1; d <= daysInMonth; d++) {
        const dateKey = `${month}-${pad(d)}`;
        if (dateKey in balanceMap) running = balanceMap[dateKey];
        days.push({
          date: dateKey,
          transactions: byDay.get(dateKey) ?? [],
          cash_flow: nonCcFlowByDay[dateKey] ?? 0,
          invoice_payments: invoiceTotalByDay[dateKey] ?? 0,
          projected_balance_end_of_day: running
        });
      }
      const payload = {
        month,
        starting_balance: startingBalance,
        total_income: totals.totalIncome,
        total_expense: totals.totalExpense,
        month_balance: totals.balance,
        projected_end_of_month_balance: totals.projectedBalance,
        invoice_total: invoiceTotals.total,
        largest_category: totals.largestCategory,
        days
      };
      return {
        content: [{ type: "text", text: JSON.stringify(payload) }],
        structuredContent: payload
      };
    } catch (error) {
      return toolError("Falha ao projetar o m\xEAs", error);
    }
  }
});

// src/lib/mcp/tools/delete-transaction.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^4.4.3";
var delete_transaction_default = defineTool8({
  name: "delete_transaction",
  title: "Excluir transa\xE7\xE3o",
  description: "Exclui uma transa\xE7\xE3o (despesa ou receita) do usu\xE1rio autenticado pelo id. Para parcelamentos, use scope='group' para remover todas as parcelas do mesmo grupo. A\xE7\xE3o irrevers\xEDvel: confirme com o usu\xE1rio antes de chamar.",
  inputSchema: {
    id: z5.string().uuid().describe("ID da transa\xE7\xE3o a excluir."),
    scope: z5.enum(["single", "group"]).optional().describe(
      "'single' (padr\xE3o) remove apenas esta transa\xE7\xE3o; 'group' remove todas as parcelas do mesmo installment_group_id."
    )
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false },
  handler: async ({ id, scope }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    try {
      const sb = supabaseForUser(ctx);
      const userId = ctx.getUserId();
      const { data: target, error: findError } = await sb.from("expenses").select("id,date,description,value,type,installment_group_id,is_recurring").eq("id", id).eq("user_id", userId).maybeSingle();
      if (findError) return toolError("Falha ao localizar a transa\xE7\xE3o", findError);
      if (!target) {
        return {
          content: [{ type: "text", text: "Transa\xE7\xE3o n\xE3o encontrada para este usu\xE1rio." }],
          isError: true
        };
      }
      const deleteGroup = scope === "group" && !!target.installment_group_id;
      const query = sb.from("expenses").delete().eq("user_id", userId);
      const { data: deleted, error: deleteError } = deleteGroup ? await query.eq("installment_group_id", target.installment_group_id).select("id") : await query.eq("id", id).select("id");
      if (deleteError) return toolError("Falha ao excluir a transa\xE7\xE3o", deleteError);
      const count = deleted?.length ?? 0;
      return {
        content: [
          {
            type: "text",
            text: `Exclu\xEDda(s) ${count} transa\xE7\xE3o(\xF5es): "${target.description}" (${target.date}).`
          }
        ],
        structuredContent: {
          deleted_count: count,
          deleted_ids: (deleted ?? []).map((d) => d.id),
          scope: deleteGroup ? "group" : "single",
          transaction: target
        }
      };
    } catch (error) {
      return toolError("Erro de conex\xE3o com o banco de dados", error);
    }
  }
});

// src/lib/mcp/tools/search.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z6 } from "npm:zod@^4.4.3";
var search_default = defineTool9({
  name: "search",
  title: "Buscar transa\xE7\xF5es",
  description: "Busca transa\xE7\xF5es (despesas e receitas) do usu\xE1rio autenticado por texto livre na descri\xE7\xE3o, categoria ou m\xEAs (YYYY-MM). Retorna uma lista de resultados com id, t\xEDtulo e resumo para depois usar a ferramenta fetch.",
  inputSchema: {
    query: z6.string().trim().min(1).describe("Termo de busca: descri\xE7\xE3o, categoria ou m\xEAs no formato YYYY-MM.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const monthMatch = query.match(/(\d{4})-(\d{2})/);
    let q = sb.from("expenses").select("id,date,description,value,type,final_category,is_paid,payment_method").order("date", { ascending: false }).limit(50);
    if (monthMatch) {
      const [, ys, ms] = monthMatch;
      const y = Number(ys);
      const m = Number(ms);
      const start = `${ys}-${ms}-01`;
      const end = new Date(Date.UTC(y, m, 0)).toISOString().slice(0, 10);
      q = q.gte("date", start).lte("date", end);
    } else {
      const term = `%${query}%`;
      q = q.or(`description.ilike.${term},final_category.ilike.${term}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const results = (data ?? []).map((r) => ({
      id: r.id,
      title: `${r.date} \u2014 ${r.description} (${r.type === "income" ? "receita" : "despesa"} R$ ${Number(r.value).toFixed(2)})`,
      text: `Categoria: ${r.final_category ?? "sem categoria"}. ${r.is_paid ? "Pago/recebido" : "Pendente"}. Forma: ${r.payment_method ?? "n/d"}.`,
      url: null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify({ results }) }],
      structuredContent: { results }
    };
  }
});

// src/lib/mcp/tools/fetch.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z7 } from "npm:zod@^4.4.3";
var fetch_default = defineTool10({
  name: "fetch",
  title: "Abrir transa\xE7\xE3o",
  description: "Retorna todos os detalhes de uma transa\xE7\xE3o do usu\xE1rio autenticado a partir do id devolvido pela ferramenta search.",
  inputSchema: {
    id: z7.string().trim().min(1).describe("ID da transa\xE7\xE3o (uuid).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("expenses").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: `Transa\xE7\xE3o ${id} n\xE3o encontrada para este usu\xE1rio.` }],
        isError: true
      };
    }
    const document = {
      id: data.id,
      title: `${data.date} \u2014 ${data.description}`,
      text: JSON.stringify(data),
      url: null,
      metadata: {
        type: data.type,
        value: Number(data.value),
        category: data.final_category ?? null,
        is_paid: Boolean(data.is_paid)
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(document) }],
      structuredContent: document
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nvskvrgsfzaynotdgzoy";
setLogLevel("info");
var mcp_default = defineMcp({
  name: "lumnia-mcp",
  title: "Lumnia",
  version: "0.2.2",
  instructions: "Ferramentas para o app Lumnia (gest\xE3o financeira pessoal). Use search para localizar transa\xE7\xF5es por texto ou m\xEAs (YYYY-MM) e fetch para abrir os detalhes de um id encontrado. Use list_transactions/month_summary para consultar dados, create_transaction para lan\xE7ar despesas ou receitas, delete_transaction para excluir uma transa\xE7\xE3o (confirme com o usu\xE1rio antes, \xE9 irrevers\xEDvel), month_transactions para ver, dia a dia, todas as transa\xE7\xF5es de um m\xEAs com o saldo projetado ao final de cada dia, e list_categories/list_wallets/list_credit_cards para contexto do usu\xE1rio.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated",
    // O ChatGPT pode concluir o OAuth com um token de sessão válido que não
    // inclui client_id/azp. Issuer, assinatura e audience continuam obrigatórios.
    requireOAuthClientClaim: false
  }),
  tools: [
    search_default,
    fetch_default,
    list_transactions_default,
    create_transaction_default,
    list_categories_default,
    month_summary_default,
    list_wallets_default,
    list_credit_cards_default,
    month_transactions_default,
    delete_transaction_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
