// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-transactions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabaseClient.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-transactions.ts
var list_transactions_default = defineTool({
  name: "list_transactions",
  title: "Listar transa\xE7\xF5es",
  description: "Lista despesas e receitas do usu\xE1rio autenticado em um intervalo de datas (padr\xE3o: \xFAltimos 30 dias). Retorna id, data, descri\xE7\xE3o, valor, tipo, categoria, se est\xE1 paga e forma de pagamento.",
  inputSchema: {
    start_date: z.string().optional().describe("Data inicial ISO (YYYY-MM-DD). Padr\xE3o: 30 dias atr\xE1s."),
    end_date: z.string().optional().describe("Data final ISO (YYYY-MM-DD). Padr\xE3o: hoje."),
    type: z.enum(["income", "expense", "transfer"]).optional().describe("Filtrar por tipo."),
    limit: z.number().int().min(1).max(500).optional().describe("M\xE1ximo de registros (padr\xE3o 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const today = /* @__PURE__ */ new Date();
    const end = end_date ?? today.toISOString().slice(0, 10);
    const start = start_date ?? new Date(today.getTime() - 30 * 864e5).toISOString().slice(0, 10);
    const sb = supabaseForUser(ctx);
    let q = sb.from("expenses").select(
      "id,date,description,value,type,final_category,is_paid,payment_method,credit_card_id,wallet_id,invoice_month,is_recurring"
    ).gte("date", start).lte("date", end).order("date", { ascending: false }).limit(limit ?? 100);
    if (type) q = q.eq("type", type);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { transactions: data ?? [], start_date: start, end_date: end }
    };
  }
});

// src/lib/mcp/tools/create-transaction.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var create_transaction_default = defineTool2({
  name: "create_transaction",
  title: "Criar transa\xE7\xE3o",
  description: "Cria uma nova despesa ou receita para o usu\xE1rio autenticado. Use tipo 'expense' para despesa e 'income' para receita.",
  inputSchema: {
    description: z2.string().min(1).describe("Descri\xE7\xE3o curta da transa\xE7\xE3o."),
    value: z2.number().positive().describe("Valor absoluto (positivo) em BRL."),
    date: z2.string().describe("Data ISO YYYY-MM-DD."),
    type: z2.enum(["expense", "income"]).describe("Tipo da transa\xE7\xE3o."),
    category: z2.string().optional().describe("Nome/slug da categoria final."),
    is_paid: z2.boolean().optional().describe("Se j\xE1 foi pago/recebido. Padr\xE3o: true."),
    notes: z2.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("expenses").insert({
      user_id: ctx.getUserId(),
      description: input.description,
      value: input.value,
      date: input.date,
      type: input.type,
      final_category: input.category ?? "outros",
      category_ai: input.category ?? "outros",
      is_paid: input.is_paid ?? true,
      notes: input.notes ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Criada: ${data.id}` }],
      structuredContent: { transaction: data }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "Listar categorias",
  description: "Lista todas as categorias e subcategorias do usu\xE1rio autenticado.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("categories").select("id,name,icon,color,parent_id,active,sort_order").order("sort_order");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/month-summary.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
var month_summary_default = defineTool4({
  name: "month_summary",
  title: "Resumo do m\xEAs",
  description: "Resume receitas, despesas e saldo do m\xEAs informado (YYYY-MM). Considera transa\xE7\xF5es pagas e agrupa despesas por categoria.",
  inputSchema: {
    month: z3.string().regex(/^\d{4}-\d{2}$/).describe("M\xEAs no formato YYYY-MM.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ month }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const start = `${month}-01`;
    const [y, m] = month.split("-").map(Number);
    const endDate = new Date(Date.UTC(y, m, 0));
    const end = endDate.toISOString().slice(0, 10);
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("expenses").select("value,type,final_category,is_paid").gte("date", start).lte("date", end);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    let income = 0;
    let expense = 0;
    const byCategory = {};
    for (const r of data ?? []) {
      if (!r.is_paid) continue;
      if (r.type === "income") income += Number(r.value);
      else if (r.type === "expense") {
        expense += Number(r.value);
        byCategory[r.final_category ?? "outros"] = (byCategory[r.final_category ?? "outros"] ?? 0) + Number(r.value);
      }
    }
    const summary = { month, income, expense, balance: income - expense, byCategory };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-wallets.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
var list_wallets_default = defineTool5({
  name: "list_wallets",
  title: "Listar carteiras",
  description: "Lista carteiras e ativos do usu\xE1rio com saldo atual e moeda.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_i, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("wallets").select("id,name,asset_type,current_balance,initial_balance,currency");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { wallets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-credit-cards.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
var list_credit_cards_default = defineTool6({
  name: "list_credit_cards",
  title: "Listar cart\xF5es de cr\xE9dito",
  description: "Lista cart\xF5es de cr\xE9dito do usu\xE1rio com limite, dia de fechamento e vencimento.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_i, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("credit_cards").select("id,name,limit_amount,closing_day,due_day,closing_strategy");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { credit_cards: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nvskvrgsfzaynotdgzoy";
var mcp_default = defineMcp({
  name: "lumnia-mcp",
  title: "Lumnia",
  version: "0.1.0",
  instructions: "Ferramentas para o app Lumnia (gest\xE3o financeira pessoal). Use list_transactions/month_summary para consultar dados, create_transaction para lan\xE7ar despesas ou receitas, e list_categories/list_wallets/list_credit_cards para contexto do usu\xE1rio.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_transactions_default,
    create_transaction_default,
    list_categories_default,
    month_summary_default,
    list_wallets_default,
    list_credit_cards_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
